<a href="https://colab.research.google.com/github/alvaro-salgado/AA_MCD/blob/main/Trea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 2


Importar las librerías, en este caso se usarán Pandas y Numpy

In [ ]:
import pandas as pd
import numpy as np

Cargar el conjunto de datos [Reconocimiento de Actividad Humana con Teléfonos Inteligentes](https://www.kaggle.com/datasets/uciml/human-activity-recognition-with-smartphones?select=test.csv "Title")

In [35]:
df = pd.read_csv('test.csv')


Visualizar algunos datos del conjunto

In [ ]:
df.sample(10)

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
1348           0.301278          -0.024704          -0.116719   
1568           0.279060          -0.013353          -0.099546   
175            0.277045          -0.016760          -0.109192   
270            0.198425          -0.027514          -0.047399   
324            0.273212          -0.009640          -0.100774   
1127           0.257988          -0.015177          -0.100281   
2172           0.245517           0.024122          -0.001161   
2804           0.284481          -0.000900          -0.127062   
2013           0.162668          -0.029567          -0.109598   
1773           0.282567          -0.019075          -0.100776   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
1348         -0.288425         -0.143362         -0.346703         -0.341429   
1568         -0.997332         -0.992167         -0.984624         -0.997933   
175          -0.994602         -0.989112         -0.986945         -0.994941   
270           0.215557          0.524874         -0.284407          0.123563   
324          -0.990645         -0.922268         -0.968321         -0.991221   
1127         -0.984813         -0.970984         -0.987562         -0.987157   
2172         -0.281765         -0.331751         -0.303740         -0.347674   
2804         -0.982404         -0.855595         -0.940217         -0.984605   
2013         -0.400005         -0.262552         -0.413488         -0.447339   
1773         -0.990124         -0.980271         -0.990982         -0.991722   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
1348         -0.185376         -0.360718          0.069910  ...   
1568         -0.990354         -0.983501         -0.942123  ...   
175          -0.989284         -0.989332         -0.937174  ...   
270           0.456439         -0.260500          0.538545  ...   
324          -0.928512         -0.967561         -0.933312  ...   
1127         -0.976911         -0.989374         -0.938460  ...   
2172         -0.352003         -0.303266          0.035788  ...   
2804         -0.872699         -0.935568         -0.929349  ...   
2013         -0.229911         -0.371484         -0.204378  ...   
1773         -0.980433         -0.993071         -0.925634  ...   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
1348                         0.067293                    -0.662498   
1568                        -0.683889                     0.039592   
175                         -0.809325                     0.409112   
270                         -0.625936                     0.294637   
324                         -0.623712                     0.110414   
1127                        -0.539490                     0.069485   
2172                        -0.532712                     0.303982   
2804                        -0.453875                    -0.144596   
2013                        -0.926435                     0.652591   
1773                        -0.047217                     0.057860   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
1348                              0.532705                         -0.867696   
1568                              0.083181                         -0.400772   
175                              -0.308401                          0.575248   
270                              -0.739213                         -0.970505   
324                               0.369169                          0.353465   
1127                              0.055992                          0.138322   
2172                             -0.172043                         -0.918556   
2804                             -0.035165                          0.455756   
2013                             -0.690304                         -0.697761   
1773                             -0.224268                          0.003060   

      angle(tBodyGy

Basado en la documentación del conjunto de datos, para cada registro se tiene:
- Aceleración triaxial del acelerómetro (aceleración total) y la aceleración corporal estimada.
- Velocidad angular triaxial del giroscopio.
- Un vector de 561 características con variables en el dominio del tiempo y la frecuencia.
- Su etiqueta de actividad.
- Un identificador del sujeto que realizó el experimento.

Revisar los tipos de datos de cada columna

In [ ]:
df.dtypes

tBodyAcc-mean()-X       float64
tBodyAcc-mean()-Y       float64
tBodyAcc-mean()-Z       float64
tBodyAcc-std()-X        float64
tBodyAcc-std()-Y        float64
                         ...   
angle(X,gravityMean)    float64
angle(Y,gravityMean)    float64
angle(Z,gravityMean)    float64
subject                   int64
Activity                 object
Length: 563, dtype: object

La mayoría de las columnas tienen float64 como tipo de dato ya que estos registros provienen de sensores

In [38]:
df.subject.unique()

array([ 2,  4,  9, 10, 12, 13, 18, 20, 24])

Se crearán dos grupos del conunto de datos, el primero contiene a los sujetos con identificador 1-12 y el siguiente 13-30

Dado que el total de los sujetos fue dividido en 2 conjuntos de datos *train y test* los grupos no contendrán todos los sujetos.

In [40]:
df_1 = df[df['subject'] <= 12].copy()
df_2 = df[df['subject'] >= 13].copy()

In [41]:
df_1.subject.unique()

array([ 2,  4,  9, 10, 12])

In [42]:
df_2.subject.unique()

array([13, 18, 20, 24])

Se creará un grupo de registros del grupo 1 en el que la actividad realizada fue caminar

In [46]:
df_1_walk = df_1[df_1['Activity'] == 'WALKING'].copy()
df_1_walk[['subject','Activity']]

subject Activity
79          2  WALKING
80          2  WALKING
81          2  WALKING
82          2  WALKING
83          2  WALKING
...       ...      ...
1470       12  WALKING
1471       12  WALKING
1472       12  WALKING
1473       12  WALKING
1474       12  WALKING

[274 rows x 2 columns]

Mientras que para el gupo 2 se seleccionarán solo los registros donde la actividad fue subir escaleras

In [48]:
df_2_stairs = df_2[df_2['Activity'] == 'WALKING_UPSTAIRS'].copy()
df_2_stairs[['subject','Activity']]

subject          Activity
1662       13  WALKING_UPSTAIRS
1663       13  WALKING_UPSTAIRS
1664       13  WALKING_UPSTAIRS
1665       13  WALKING_UPSTAIRS
1666       13  WALKING_UPSTAIRS
...       ...               ...
2942       24  WALKING_UPSTAIRS
2943       24  WALKING_UPSTAIRS
2944       24  WALKING_UPSTAIRS
2945       24  WALKING_UPSTAIRS
2946       24  WALKING_UPSTAIRS

[223 rows x 2 columns]